/**
 * user_filter_prefs frontend helpers
 *
 * @version 1.1.1
 * @author plcats
 */
(function () {
    function appendApplyMarker(urlStr) {
        try {
            var url = new URL(urlStr, window.location.origin);
            url.searchParams.set('-ufp-apply', '1');
            return url.toString();
        } catch (e) {
            return urlStr;
        }
    }

    function hookDesktopResultFilters() {
        if (typeof window.resultlist__updateFilters !== 'function') {
            return false;
        }

        if (window.__ufpDesktopFiltersHooked) {
            return true;
        }

        var originalUpdateFilters = window.resultlist__updateFilters;
        window.resultlist__updateFilters = function (col, select, currentURL) {
            var manualRedirect = !currentURL;
            var baseUrl = manualRedirect ? window.location.href : currentURL;
            var nextUrl = originalUpdateFilters.call(this, col, select, baseUrl);

            if (typeof nextUrl !== 'string') {
                return nextUrl;
            }

            nextUrl = appendApplyMarker(nextUrl);
            if (manualRedirect) {
                window.location = nextUrl;
                return;
            }

            return nextUrl;
        };

        window.__ufpDesktopFiltersHooked = true;
        return true;
    }

    function markApplyInFilterDialog() {
        // Only run inside the mobile filter dialog iframe context.
        if (typeof window.applyFilters !== 'function') {
            return false;
        }

        if (window.__ufpApplyHooked) {
            return true;
        }

        window.applyFilters = function () {
            try {
                if (typeof window.syncFiltersFromForm === 'function') {
                    window.syncFiltersFromForm();
                }

                if (typeof window.filterSearch === 'string') {
                    // Remove no-filter placeholders generated by mobile dialog.
                    window.filterSearch = sanitizeFilterSearch(window.filterSearch);
                }

                if (typeof window.updateFieldValue === 'function') {
                    // Keep legacy marker expected by existing server-side flows.
                    window.updateFieldValue('-xf-filter-apply', '1');
                    window.updateFieldValue('-ufp-apply', '1');
                } else if (typeof window.filterSearch === 'string') {
                    if (window.filterSearch.indexOf('-xf-filter-apply=') === -1) {
                        window.filterSearch += '&-xf-filter-apply=1';
                    }
                    if (window.filterSearch.indexOf('-ufp-apply=') === -1) {
                        window.filterSearch += '&-ufp-apply=1';
                    }
                }

                if (window.win && window.win.activeSheet) {
                    window.win.activeSheet.close();
                }

                if (window.win && window.win.jQuery) {
                    window.win.jQuery('<div class="spin fillscreen"></div>').appendTo(window.win.document.body);
                }

                if (window.win && typeof window.win.location !== 'undefined' && typeof window.filterSearch === 'string') {
                    window.win.location.replace(window.filterSearch);
                    return false;
                }

            } catch (e) {
                // Best-effort marker injection; preserve original behavior on errors.
            }

            return false;
        };

        window.__ufpApplyHooked = true;
        return true;
    }

    function sanitizeFilterSearch(search) {
        if (typeof search !== 'string' || search.length === 0) {
            return search;
        }

        var q = search.charAt(0) === '?' ? search.substring(1) : search;
        var params = new URLSearchParams(q);
        var toDelete = [];

        params.forEach(function (value, key) {
            // '=' is Xataface "All" marker, not an active filter.
            if (value === '=' && key.charAt(0) !== '-') {
                toDelete.push(key);
            }
        });

        toDelete.forEach(function (k) {
            params.delete(k);
        });

        var next = params.toString();
        return next ? ('?' + next) : '?';
    }

    if (!hookDesktopResultFilters()) {
        var desktopAttempts = 0;
        var desktopTimer = setInterval(function () {
            desktopAttempts += 1;
            if (hookDesktopResultFilters() || desktopAttempts > 40) {
                clearInterval(desktopTimer);
            }
        }, 100);
    }

    if (!markApplyInFilterDialog()) {
        var attempts = 0;
        var timer = setInterval(function () {
            attempts += 1;
            if (markApplyInFilterDialog() || attempts > 20) {
                clearInterval(timer);
            }
        }, 150);
    }
})();
